# Generated by Django 5.2.1 on 2025-06-10 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025)),
                ('grade', models.CharField(max_length=1)),
                ('acronym', models.CharField(max_length=2)),
                ('average_annual_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average_annual_attendance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grades.grade')),
                ('teacherSubject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teachersubject')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_Participation', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('average_attendance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('average_tasks', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('average_exam', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('average_Note', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('state', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.grade')),
            ],
            options={
                'unique_together': {('grade', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_repeater', models.BooleanField(default=False)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'grade')},
            },
        ),
    ]
