# Generated by Django 5.2.1 on 2025-06-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='degreesubject',
            unique_together={('grade', 'subject')},
        ),
    ]
