services:
  db:
    image: postgres:15
    container_name: segundo_parcial_db
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: segundo_parcial_pgadmin
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: Docker/DockerfileBackend
    container_name: segundo_parcial_backend
    volumes:
      - ./backend:/app/backend
    env_file: .env
    command: ["bash", "/app/Docker/entrypoint.sh"]
    depends_on:
      - db
    ports:
      - "8000:8000"


  frontend:
    build:
      context: .
      dockerfile: Docker/DockerfileFrontend
    container_name: segundo_parcial_frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    working_dir: /app/frontend
    command: ["sh", "-c", "npm install && npm start"]
    stdin_open: true
    tty: true
    ports:
      - "4200:4200"
    depends_on:
      - backend


volumes:
  db_data: