version: '3.8'

services:
  db:
    image: postgres:15
    container_name: segundo_parcial_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: segundo_parcial
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: segundo_parcial_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build:
      context: ./backend
    container_name: segundo_parcial_backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/segundo_parcial
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: segundo_parcial_frontend
    ports:
      - "4200:4200" # Mapea el puerto 4200 del contenedor al host
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  db_data: