# Generated by Django 5.2.1 on 2025-06-13 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('student_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('created_year', models.IntegerField(default=2025)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('rol', models.CharField(choices=[('F', 'Padre'), ('M', 'Madre'), ('O', 'Otro')], max_length=1)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('tutor_email', models.EmailField(max_length=254, unique=True)),
                ('created_year', models.IntegerField(default=2025)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
