# Generated by Django 5.2.1 on 2025-06-01 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quetar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Asistencia'), ('T', 'Tarea'), ('P', 'Participacion'), ('E', 'Examen')], max_length=1)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('degree_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.degreesubject')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
                ('quetar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quater.quetar')),
            ],
        ),
    ]
