# Generated by Django 5.2.1 on 2025-06-10 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quetar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queter', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_Task', models.FloatField(default=0)),
                ('note_Exam', models.FloatField(default=0)),
                ('note_Participation', models.FloatField(default=0)),
                ('note_Attendance', models.FloatField(default=0)),
                ('note', models.FloatField(default=0)),
                ('degreeSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.degreesubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('quetar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quater.quetar')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Asistencia'), ('T', 'Tarea'), ('P', 'Participacion'), ('E', 'Examen')], max_length=1)),
                ('note_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField(auto_now_add=True)),
                ('degreeSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.degreesubject')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quater.notes')),
            ],
        ),
        migrations.CreateModel(
            name='TareaUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('end_date', models.DateField()),
                ('followUp', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quater.followup')),
            ],
        ),
    ]
