# Generated by Django 5.2.1 on 2025-06-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quater', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='degree_subject',
            new_name='degreeSubject',
        ),
    ]
