# Generated by Django 5.2.1 on 2025-06-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quater', '0002_remove_tareaurl_followup_remove_tareaurl_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TareaUrl',
        ),
    ]
