# Generated by Django 5.2.1 on 2025-06-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='grade_id',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='groupteacher',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupteacher',
            old_name='teacher_subject_id',
            new_name='teacherSubject',
        ),
    ]
